// vue-3-crud-with-rest-api-integration/src/components/Author.vue
<template>
  <v-container>
    <h1>Author Management UI</h1>
    <p>This UI developed to handle Author Registration.</p>
    <v-row>
      <v-col sm="6">
        <h3>Author Registration</h3>
        <v-text-field
          v-model="userRegistration.firstName"
          label="First name"
        ></v-text-field>
        <v-text-field
          v-model="userRegistration.lastName"
          label="Last name"
        ></v-text-field>
        <v-btn color="primary" v-on:click="createAuthor">
          Register
        </v-btn>
      </v-col>
      <v-col sm="6">
        <h3>Registered Authors</h3>
        <v-simple-table>
          <template v-slot:default>
            <thead>
              <tr>
                <th class="text-left">
                  ID
                </th>
                <th class="text-left">
                  First Name
                </th>
                <th class="text-left">
                  Last Name
                </th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="author in registeredAuthors" :key="author.id">
                <td>{{ author.id }}</td>
                <td>{{ author.firstName }}</td>
                <td>{{ author.lastName }}</td>
              </tr>
            </tbody>
          </template>
        </v-simple-table>
      </v-col>
    </v-row>
  </v-container>
</template>
<script>
import api from "@/service/apiService";

export default {
  name: "Author",
  data() {
    return {
      userRegistration: {
        firstName: "",
        lastName: "",
      },
      registeredAuthors: [],
    };
  },
  methods: {
    readAuthors: async function() {
      const data = await api.readAuthors();
      this.registeredAuthors = data;
    },
    createAuthor: async function() {
      const requestData = {
        firstName: this.userRegistration.firstName,
        lastName: this.userRegistration.lastName,
      };
      await api.createAuthor(requestData);
      this.userRegistration.firstName = "";
      this.userRegistration.lastName = "";
      this.readAuthors();
    },
  },
  mounted() {
    this.readAuthors();
  },
};
</script>

// springboot-angular10-crud/src/app/author/author.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, } from '@angular/forms';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-author',
  templateUrl: './author.component.html',
  styleUrls: ['./author.component.css'],
})
export class AuthorComponent implements OnInit {
  
  authors;
  authorRegistrationForm;

  constructor(
    private formBuilder: FormBuilder,
    private apiService: ApiService) {

    this.authorRegistrationForm = this.formBuilder.group({
      firstname: '',
      lastname: ''
    });

  }

  ngOnInit(): void {
    this.getAuthors();    
  }

  getAuthors() {
    this.apiService.getAllAuthors().subscribe(response=>{
      this.authors = response;
      console.log(JSON.stringify(response));
    },
    error=>{
      console.log(error)
    })
  }

  onSubmit(authorData) {
    this.authorRegistrationForm.reset();
    const user_register_data = {
      firstName: authorData.firstname,
      lastName: authorData.lastname
    };
    console.log('Your author registration successfully', authorData);
    this.apiService.createAuthor(user_register_data).subscribe(response=>{
      console.log("Author creation successfull"+ response.id);
      this.getAuthors();
    },error=>{
      console.log('Error in author registration');
    });
    
  }

}

<div class="row">
  <div class="col-md-6">
    <h4>Author Registration</h4>
    <form [formGroup]="authorRegistrationForm" (ngSubmit)="onSubmit(authorRegistrationForm.value)">      
      <div class="form-group">
        <label for="author_f_name">First Name</label>
        <input
          type="text"
          class="form-control"
          id="author_f_name"
          formControlName="firstname"
        />
      </div>
      <div class="form-group">
        <label for="author_l_name">Last Name</label>
        <input
          type="text"
          class="form-control"
          id="author_l_name"
          formControlName="lastname"
        />
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
  <div class="col-md-6">
    <h4>Registered Authors</h4>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let author of authors">
              <td>{{author.id}}</td>
              <td>{{author.firstName}}</td>
              <td>{{author.lastName}}</td>
            </tr>
        </tbody>
      </table>
  </div>
</div>
